import random
"""random lib"""


def generate_random_ip():
    return f"192.168.1.{random.randint(0, 20)}"


"""generate last bit of ip addresses bw 0 to 20"""


def check_firewall_rules(ip, rules):
    for rule_ip, action in rules.items():
        if ip == rule_ip:
            return action
        return "allow"


"""check firewall rules- basically if any random ip addresses fall in the blocked category acc to whats defined, rule_ip is the IP in the rule"""


def main():
    firewall_rules = {
        "192.168.1.1": "block",
        "192.168.1.4": "block",
        "192.168.1.9": "block",
        "192.168.1.13": "block",
        "192.168.1.16": "block",
        "192.168.1.19": "block"

    }
    """predefined rules set by us where we match the ip to action"""
    for _ in range(12):
        ip_address = generate_random_ip()
        action = check_firewall_rules(ip_address, firewall_rules)
        random_number = random.randint(0, 9999)
        print(f"IP: {ip_address}, Action: {action}, Random: {random_number}")


"""simulate network traffic by generating 12 random ips and checking them against firewall rules- basically picking first 12 random ips generated by generate_ip block and checking it against the rules, this is where calling happens, random_number is generating a random number to show the randomness and possibly a session id irl, nologic just printed"""

if __name__ == "__main__":
    main()
